version: '3'
services:
  snake1:
    image: hirethissnake
    ports:
      - "8080:8080"
    volumes:
      - ./app:/data/app
    command:
      python -m app.main
    tty: true
  snake2:
    image: hirethissnake
    ports:
      - "8081:8080"
    volumes:
      - ./app:/data/app
    command:
      python -m app.main
    tty: true
  snake3:
    image: hirethissnake
    ports:
      - "8082:8080"
    volumes:
      - ./app:/data/app
    command:
      python -m app.main
    tty: true